program Capricornius;

uses
  Forms,
  UPrincipal in 'UPrincipal.pas' {FPrincipal},
  URelFichaSecagem in 'URelFichaSecagem.pas' {ReportFichaSecagem: TQuickRep},
  UrelFichaContLeit in 'UrelFichaContLeit.pas' {ReportFichaConLeit: TQuickRep},
  UrelFichaContLeit2 in 'UrelFichaContLeit2.pas' {ReportFichaContLeit2: TQuickRep},
  UrelFichaContLeitBaia in 'UrelFichaContLeitBaia.pas' {ReportFichaLeiteBaia: TQuickRep},
  UrelFichaContLeitBaia2 in 'UrelFichaContLeitBaia2.pas' {ReportFichaLeiteBaia2: TQuickRep},
  URelFichaDesmame in 'URelFichaDesmame.pas' {ReportFichaDesmame: TQuickRep},
  URelFichaEscore in 'URelFichaEscore.pas' {ReportFichaEscore: TQuickRep},
  URelFichaNascimento in 'URelFichaNascimento.pas' {ReportFichaNascimento: TQuickRep},
  URelFichaOcorrencias in 'URelFichaOcorrencias.pas' {ReportFichaOcorrencias: TQuickRep},
  UrelFichaPesagem in 'UrelFichaPesagem.pas' {ReportFichaPesagem: TQuickRep},
  URelFichaPrenhez in 'URelFichaPrenhez.pas' {ReportFichaPrenhez: TQuickRep},
  Udatamodule in 'Udatamodule.pas' {FDataModule: TDataModule},
  URelFichaCio in 'URelFichaCio.pas' {ReportFichaCio: TQuickRep},
  UrelCriatorios in 'UrelCriatorios.pas' {ReportCriatorios: TQuickRep},
  Uentrada in 'Uentrada.pas' {Fentrada},
  UcriatorioAtual in 'UcriatorioAtual.pas' {FcriatorioAtual},
  Ucriatorio in 'Ucriatorio.pas' {Fcriatorio},
  Ufiltro in 'Ufiltro.pas' {Ffiltro},
  Ufichaind in 'Ufichaind.pas' {Ffichaind},
  UrelFichaInd in 'UrelFichaInd.pas' {ReportFichaInd: TQuickRep},
  Uselecanimrel in 'Uselecanimrel.pas' {Fselecanimaisrel},
  Uselecanimaisesp in 'Uselecanimaisesp.pas' {Fselecanimaisesp},
  UrelFemeasLact in 'UrelFemeasLact.pas' {ReportFemLact: TQuickRep},
  Uintervaloprod in 'Uintervaloprod.pas' {Fintervaloprod},
  UintervaloMaiorProd in 'UintervaloMaiorProd.pas' {FintervaloMaiorProd},
  UCamposRelAnimais in 'UCamposRelAnimais.pas' {FCamposRelAnimais},
  UrelAnimais in 'UrelAnimais.pas' {ReportRelGerAn: TQuickRep},
  UrelDadosPondOb in 'UrelDadosPondOb.pas' {ReportDadosPondOb: TQuickRep},
  UrelDadosReprod in 'UrelDadosReprod.pas' {ReportDadReprod: TQuickRep},
  UrelFemeasNaoGest in 'UrelFemeasNaoGest.pas' {ReportFemNGest: TQuickRep},
  URelLactacoes in 'URelLactacoes.pas' {ReportLactacoes: TQuickRep},
  URelMaioresProd in 'URelMaioresProd.pas' {ReportMaioresProd: TQuickRep},
  URelMedias in 'URelMedias.pas' {ReportMedias: TQuickRep},
  UrelMedPeso in 'UrelMedPeso.pas' {ReportMedPeso: TQuickRep},
  URelNascimentos in 'URelNascimentos.pas' {ReportNascimentos: TQuickRep},
  UrelOcorrencias in 'UrelOcorrencias.pas' {ReportOcorrencias: TQuickRep},
  UrelPrevPartos in 'UrelPrevPartos.pas' {ReportPrevPartos: TQuickRep},
  UrelPrevSecagem in 'UrelPrevSecagem.pas' {ReportPrevSec: TQuickRep},
  URelProdIntervalo in 'URelProdIntervalo.pas' {ReportProdIntervalo: TQuickRep},
  UOpcoesFichaLeite in 'UOpcoesFichaLeite.pas' {FOpcoesFichaLeite},
  UEstacoesMonta in 'UEstacoesMonta.pas' {FEstacoesMonta},
  UCriatorioRelatorio in 'UCriatorioRelatorio.pas' {FCriatorioRelatorio},
  URelAgenda in 'URelAgenda.pas' {RAgenda: TQuickRep},
  Uerroimport in 'Uerroimport.pas' {QRerroimport: TQuickRep},
  UErroImportProd in 'UErroImportProd.pas' {QErroImportProd: TQuickRep},
  URacaComposta in 'URacaComposta.pas' {FRacaComposta},
  UPesagens in 'UPesagens.pas' {FPesagens},
  UPesoAcasalamento in 'UPesoAcasalamento.pas' {FPesoAcasalamento},
  UErroImportPeso in 'UErroImportPeso.pas' {QErroImportPeso: TQuickRep},
  URelFichaSaida in 'URelFichaSaida.pas' {ReportFichaSaida: TQuickRep},
  Usituacao in 'Usituacao.pas' {ReportSituacao: TQuickRep},
  UImportExport in 'UImportExport.pas' {FImportExport},
  UVisualizarFoto in 'UVisualizarFoto.pas' {FVisualizarFoto},
  UInserirExcluirFoto in 'UInserirExcluirFoto.pas' {FInserirExcluirFoto},
  URelVacinacoes in 'URelVacinacoes.pas' {ReportVacinacoes: TQuickRep},
  URelFichaDoenca in 'URelFichaDoenca.pas' {ReportFichaDoenca: TQuickRep},
  URelDiagDoencas in 'URelDiagDoencas.pas' {ReportDiagnosticoDoencas: TQuickRep},
  Ufertilidade in 'Ufertilidade.pas' {ReportFertilidade: TQuickRep},
  UrelFertInd in 'UrelFertInd.pas' {ReportFertInd: TQuickRep},
  UintervaloAnos in 'UintervaloAnos.pas' {FintervaloAnos},
  UOpcoesFichaGest in 'UOpcoesFichaGest.pas' {FOpcoesFichaGest},
  UselecDep in 'UselecDep.pas' {FselecDep},
  URelDep in 'URelDep.pas' {ReportDep: TQuickRep},
  UDespesas in 'UDespesas.pas' {FDespesas},
  UReceitas in 'UReceitas.pas' {FReceitas},
  UselecAtiv in 'UselecAtiv.pas' {FselecAtiv},
  UCustoAtiv in 'UCustoAtiv.pas' {ReportCustoAtiv},
  UValidar in 'UValidar.pas' {FValidar},
  UTerras in 'UTerras.pas' {FTerras},
  UBenfeitorias in 'UBenfeitorias.pas' {FBenfeitorias},
  UMaquinas in 'UMaquinas.pas' {FMaquinas},
  UOutros in 'UOutros.pas' {FRecursosHumanos},
  UInsumos in 'UInsumos.pas' {FInsumos},
  UCompRacial in 'UCompRacial.pas' {FCompRacial},
  URelListaPesa in 'URelListaPesa.pas' {ReportListaPesagens: TQuickRep},
  URelCustoProdLeite in 'URelCustoProdLeite.pas' {ReportCustoProdLeite: TQuickRep},
  URelCustoProdCarne in 'URelCustoProdCarne.pas' {ReportCustoProdCarne: TQuickRep},
  URelCustoReprodutores in 'URelCustoReprodutores.pas' {ReportCustoVendaDeAnimais: TQuickRep},
  URelRegAssociacao in 'URelRegAssociacao.pas' {ReportRegistroAssociacao: TQuickRep},
  URelFinanGeral in 'URelFinanGeral.pas' {ReportFinanGeral: TQuickRep},
  UComparativo in 'UComparativo.pas' {ReportComparativo: TQuickRep},
  UIntervaloComp in 'UIntervaloComp.pas' {FIntervaloComparativo};

{$R *.RES}

begin
  Application.Initialize;
  Application.Title := 'Capricornius';
  Application.HelpFile := 'C:\Capricornius\HELP.HLP';
  Application.CreateForm(TFPrincipal, FPrincipal);
  Application.CreateForm(TFCompRacial, FCompRacial);
  Application.CreateForm(TReportListaPesagens, ReportListaPesagens);
  Application.Run;
end.
